# Use nginx image
FROM nginx:latest

# Copy all website files into nginx's public html directory
COPY . /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start nginx server
CMD ["nginx", "-g", "daemon off;"]
